-- MySQL Script generated by MySQL Workbench
-- Fri Oct 28 18:34:06 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema abs_facet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema abs_facet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `abs_facet` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `abs_facet` ;

-- -----------------------------------------------------
-- Table `abs_facet`.`abs_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abs_facet`.`abs_pedido` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` TEXT NULL COMMENT '',
  `tipoDocumento` VARCHAR(45) NULL COMMENT '',
  `documento` VARCHAR(15) NULL COMMENT '',
  `direccion` TEXT NULL COMMENT '',
  `apartamento` VARCHAR(75) NULL COMMENT '',
  `ciudad` VARCHAR(75) NULL COMMENT '',
  `telefono` VARCHAR(15) NULL COMMENT '',
  `email` VARCHAR(150) NULL COMMENT '',
  `celular` VARCHAR(75) NULL COMMENT '',
  `cantidadCombo1` INT NULL COMMENT '',
  `cantidadCombo2` INT NULL COMMENT '',
  `cantidadCombo3` INT NULL COMMENT '',
  `cantidadCombo4` INT NULL COMMENT '',
  `totalValor` VARCHAR(75) NULL COMMENT '',
  `fecha` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
